### ISSUE TITLE
Error in preseq lc_extrap and duplicate-remover

### ISSUE THREAD

**Issue by slzhao** [smithlabcode/methpipe#103]
Hello,

I have got some error messages in preseq lc_extrap and duplicate-remover. Would you please help with it? Thanks!

For preseq lc_extrap:

> /usr/spool/slurm/job12566213/slurm_script: line 34: 17771 Segmentation fault      (core dumped) preseq lc_extrap -D test.mr > test.mr.lc_extrap

For duplicate-remover. In fact I have sorted the .mr file, but it still says "not properly sorted". I think it is a bug to handle reads in the same position?

> input not properly sorted:
> chr1    30160078        30160118        HISEQ:507:CACFKANXX:5:1204:15116:47662  6       -       TATATATACGTGTATATAT
> GTATATATATATGTGTGTGTG   </</BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
> chr1    30160078        30160118        HISEQ:507:CACFKANXX:5:1213:12725:37119  6       +       TATATGTGTGTATATGTAT
> GTGTATATATGTTTGCGTGTG   FFFFFFBFFFFFFFFB<</FFFF/FFBFFFFBFFBBBBBB
>

**Comment by mengzhou** [comment]
Hi,

The reads should be sorted based on (1) chromosome, (2) start, (3) end, and
(4) strand. In your example the first 3 coordinates are the same, however
the strand is not properly sorted.


Best regards,
Meng

**Comment by slzhao** [comment]
Thanks! I think you are right. Let me try it.
Do you have any suggestion about the error in lc_extrap?

**Comment by timydaley** [comment]
I think the error in preseq is due to a bug in v2 and is fixed in v2.0.2.  Try updating the repo or installing v2.0.2 (https://github.com/smithlabcode/preseq/releases/tag/v2.0.2) and let me know if you still have the error.

Cheers.



Timothy Daley

Stanford University, Departments of Statistics and Bioengineering.

________________________________

**Comment by slzhao** [comment]
Thanks! Will update and report back.

**Comment by slzhao** [comment]
Hello,

Sort issue was fixed by mengzhou's method.

preseq v2.0.2 fixed the "Segmentation fault" error in defect mode. But if I removed the "-D" parameter to go back to normal mode, it says (the same as the v2.0.0 version) "ERROR:  too many defects in the approximation, consider running in defect mode".

Thanks all!

**Comment by timydaley** [comment]
I apologize that preseq still won't work for you.  Can you send me a small dataset where you encounter the error so that I can reproduce the issue and debug it?


Timothy Daley

Stanford University, Departments of Statistics and Bioengineering.

________________________________

**Comment by slzhao** [comment]
Thanks Timothy!
The .mr file has 51G size. I've tired the top 5,000,000 and tail 5,000,000 lines of that file and preseq lc_extrap runs perfectly. So I think it may be related to the very large file size and too many tests/checks in normal mode (without -D). Hopefully the -D mode will not change the result very much.

**Comment by timydaley** [comment]
@slzhao , I think I made an issue for you on the preseq repo.  Please confirm and we can work it out over there.

**Comment by slzhao** [comment]
Thanks timydaley. Replied at preseq repo
